version: "3"
services:
  frontend:
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000,http://frontend:3000
